#!/usr/bin/expect -f

send_user "Enter service \n"
expect_user -re "(.*)\n"
set service $expect_out(1,string)
send_user "Enter port \n"
expect_user -re "(.*)\n"
set port $expect_out(1,string)
spawn ssh -i ~/id_geni_ssh_rsa $service -p $port
expect "Enter passphrase for key '/home/thydo/id_geni_ssh_rsa':"
send "Mrpiggey2604!\r"
interact